apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
spec:
  description: infra tenant
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'