apiVersion: v1
kind: Secret
metadata:
  name: istio-overlay-ako
  namespace: vmware-system-tkg
stringData:
  istio-overlay.yaml: |
    #@ load("@ytt:overlay", "overlay")

    #@overlay/match by=overlay.subset({"kind": "StatefulSet", "metadata": {"name": "ako"}})
    ---
    spec:
      template:
        metadata:
          #@overlay/match missing_ok=True
          annotations:
            #@overlay/merge
            traffic.sidecar.istio.io/includeInboundPorts: ""
            traffic.sidecar.istio.io/includeOutboundIPRanges: ""
            proxy.istio.io/config: |
              proxyMetadata:
                OUTPUT_CERTS: /etc/istio-output-certs
            sidecar.istio.io/userVolume: '[{"name": "istio-certs", "emptyDir": {"medium":"Memory"}}]'
            sidecar.istio.io/userVolumeMount: '[{"name": "istio-certs", "mountPath": "/etc/istio-output-certs"}]'
        spec:
        #@overlay/match missing_ok=True
          volumes:
          #@overlay/append
          - name: istio-certs
            emptyDir:
              medium: Memory

    ---

    #@overlay/match by=overlay.subset({"kind": "Namespace", "metadata": {"name": "avi-system"}})
    ---
    metadata:
      #@overlay/match missing_ok=True
      labels:
        #@overlay/match missing_ok=True
        istio-injection: enabled
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '3'
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: istio-overlay-ako
  name: dev1-cluster-ako
  namespace: vmware-system-tkg
# spec:
#   values:
#     - secretRef:
#         name: dev1-cluster-ako-data-values