apiVersion: v1
kind: Secret
metadata:
  name: telegraf-values
stringData:
  values.yml: |
    domainName: cluster.local
    isMetricProxyConfigured: true
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: telegraf
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  packageRef:
    refName: telegraf.kubernetes.vmware.com
    versionSelection:
      constraints: 1.37.1+vmware.1-vks.1
      prereleases: {}
  serviceAccountName: carvel-sa
  values:
  - secretRef:
      name: telegraf-values