# Generated by scripts/generate-bootstrap.py — do not edit manually.
# Re-run `make generate` after editing terraform/infra/tenants.yaml.

module "bootstrap_tenant_1_dev_1" {
  source = "../modules/bootstrap-helm"

  providers = { helm = helm.tenant_1_dev_1 }

  namespace           = "dev-1"
  tenant_name         = "tenant-1"
  deploy_argo         = false
  argo_namespace      = "infra"
  argo_password       = var.argo_password
  argo_cluster_labels = {
    type = "supervisor-ns"
  }
  ako_secret_enabled  = var.ako_secret_enabled
  ako_username        = var.ako_username
  ako_password        = var.ako_password
  ako_ca_data         = var.ako_ca_data
}

module "bootstrap_infra_1_infra" {
  source = "../modules/bootstrap-helm"

  providers = { helm = helm.infra_1_infra }

  namespace           = "infra"
  tenant_name         = "infra-1"
  deploy_argo         = true
  argo_namespace      = "infra"
  argo_password       = var.argo_password
  argo_cluster_labels = {
    type = "supervisor-ns"
  }
  ako_secret_enabled  = var.ako_secret_enabled
  ako_username        = var.ako_username
  ako_password        = var.ako_password
  ako_ca_data         = var.ako_ca_data
}
