# Generated by terraform/infra (local_file) — do not edit manually.
# Re-rendered by `make apply-infra` whenever the set of namespaces changes.
# Per-namespace helm providers (Terraform cannot for_each provider configs).
# Tokens are minted fresh on every run by data.vcfa_kubeconfig.ns (vcfa.tf),
# keyed by var.namespace_config — no kubeconfigs are shuttled from the infra run.

provider "helm" {
  alias = "tenant_1_dev_1"
  kubernetes = {
    host     = data.vcfa_kubeconfig.ns["tenant-1-dev-1"].host
    token    = data.vcfa_kubeconfig.ns["tenant-1-dev-1"].token
    insecure = data.vcfa_kubeconfig.ns["tenant-1-dev-1"].insecure_skip_tls_verify
  }
}

provider "helm" {
  alias = "infra_1_infra"
  kubernetes = {
    host     = data.vcfa_kubeconfig.ns["infra-1-infra"].host
    token    = data.vcfa_kubeconfig.ns["infra-1-infra"].token
    insecure = data.vcfa_kubeconfig.ns["infra-1-infra"].insecure_skip_tls_verify
  }
}
