# Generated by terraform/infra (local_file) — do not edit manually.
# Re-rendered by `make apply-infra` whenever the set of namespaces changes.
# Per-namespace helm providers (Terraform cannot for_each provider configs).

provider "helm" {
  alias = "tenant_1_dev_1"
  kubernetes = {
    host     = var.kubeconfigs["tenant-1-dev-1"].host
    token    = var.kubeconfigs["tenant-1-dev-1"].token
    insecure = var.kubeconfigs["tenant-1-dev-1"].insecure_skip_tls_verify
  }
}

provider "helm" {
  alias = "infra_1_infra"
  kubernetes = {
    host     = var.kubeconfigs["infra-1-infra"].host
    token    = var.kubeconfigs["infra-1-infra"].token
    insecure = var.kubeconfigs["infra-1-infra"].insecure_skip_tls_verify
  }
}
