#@ load("@ytt:data", "data")
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: #@ data.values.name
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: #@ data.values.name
  sourceRepos:
  - "*"
  destinations:
  - namespace: "*"
    server: "*"
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
  #@ if data.values.type == "infra":
  namespaceResourceWhitelist:
  - group: "*"
    kind: "*"
  #@ end
