apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-provisioning
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: ARGOCD_REPO_URL
      revision: main
      directories:
      - path: infrastructure/clusters/*/*/*
  template:
    metadata:
      name: '{{ index (splitList "/" .path) 2 }}-{{ .path.basename }}-provision'
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      labels:
        tenant: '{{ index (splitList "/" .path) 2 }}'
        type: "cluster-infrastructure"
    spec:
      project: infra
      source:
        repoURL: ARGOCD_REPO_URL
        targetRevision: main
        path: '{{ .path }}'
      destination:
        name: 'supervisor-ns-{{ index (splitList "/" .path) 3 }}'
        namespace: '{{ index (splitList "/" .path) 3 }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
