apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
        - clusters:
            selector:
              matchLabels:
                type: 'tenant'
            values:
              project: '{{index .metadata.labels "project"}}'
        - git:
            repoURL: ARGOCD_REPO_URL
            revision: main
            directories:
            - path: 'infrastructure/clusters/{{.values.project}}/*/{{.name}}/apps'
  template:
    metadata:
      name: '{{.name}}-apps'
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: 'infra'
      source:
        repoURL: ARGOCD_REPO_URL
        targetRevision: main
        path: '{{.path}}'
      destination:
        server: '{{.server}}'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
