apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-provisioning
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  generators:
  - git:
      repoURL: https://github.com/warroyo/argocd-scaffolding
      revision: main
      files:
      - path: infrastructure/clusters/*/*/cluster-details.yaml
  template:
    metadata:
      name: '{{data.project}}-{{data.cluster_name}}-provision'
      finalizers:
      - resources-finalizer.argocd.argoproj.io
      labels:
        tenant: '{{data.project}}'
        type: "cluster-infrastructure"
    spec:
      project: infra
      source:
        repoURL: https://github.com/warroyo/argocd-scaffolding
        targetRevision: main
        path: '{{path}}'
      destination:
        name:  'supervisor-ns-{{data.namespace}}'
        namespace: '{{data.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
