apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchLabels:
          type: 'tenant'
  template:
    metadata:
      name: '{{.name}}-apps'
    spec:
      project: 'standard-project'
      source:
        repoURL: https://github.com/warroyo/argocd-scaffolding
        targetRevision: main
        path: apps/clusters/{{.name}}
      destination:
        server: '{{.server}}'
        namespace: argocd
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
