---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cert-manager
  namespace: infra-packages
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  packageRef:
    refName: cert-manager.kubernetes.vmware.com
    versionSelection:
      # Placeholder — version supplied by apps/components/envs/{env}.
      constraints: replace-me
      prereleases: {}
  serviceAccountName: carvel-sa