# Opt out of automated observability: flip the automated-monitoring addon label
# (enabled by default in base/vks-cluster) to disabled.
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
- target:
    group: cluster.x-k8s.io
    version: v1beta1
    kind: Cluster
  patch: |-
    - op: replace
      path: /metadata/labels/addons.kubernetes.vmware.com~1automated-monitoring
      value: disabled
