apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../../../../../../apps/components/stacks/standard
- ../../../../../../apps/components/envs/dev
# Uncomment to enable optional stacks:
# - ../../../../../../apps/components/stacks/observability
# - ../../../../../../apps/components/stacks/service-mesh
# To enable Istio AKO patch, also add under resources:
# resources:
# - ../../../../../../apps/base/istio-ako-patch
