apiVersion: v1
kind: ConfigMap
metadata:
  name: vars
  annotations:
    config.kubernetes.io/local-config: 'true'
data:
  cluster_name: my-cluster   # must equal this directory name
  project: my-tenant         # must equal the {project} directory & cluster label
  namespace_ref: my-ns       # must equal the {namespace_ref} directory & cluster label
