apiVersion: v1
kind: ConfigMap
metadata:
  name: vars
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  argo_namespace: "infra-ty3qk"
  namespace: "dev-1-wyt7g"
  cluster_name: "dev1-cluster"
  project: "tenant-1"