apiVersion: apps/v1
kind: Deployment
metadata:
  name: istiod
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: istiod
  template:
    metadata:
      labels:
        app: istiod
    spec:
      containers:
      - image: gcr.io/istio/pilot:1.15.0
        name: discovery
        ports:
        - containerPort: 15010
        - containerPort: 15012
        resources:
          requests:
            cpu: 500m
            memory: 2048Mi
---
apiVersion: v1
kind: Service
metadata:
  name: istiod
  namespace: istio-system
spec:
  ports:
  - port: 15010
    name: grpc-xds
  - port: 15012
    name: https-dns
  selector:
    app: istiod
