#!/usr/bin/env python3
"""Populate auto-generated values into tenant-vars.yaml and cluster-details.yaml after Terraform apply.
Run via: make generate-details
Requires: terraform/infra/ must be initialized and have state (terraform output must succeed).
"""

import json, os, subprocess, sys, yaml

REPO_ROOT    = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TENANTS_FILE = os.path.join(REPO_ROOT, "terraform", "infra", "tenants.yaml")
INFRA_DIR    = os.path.join(REPO_ROOT, "terraform", "infra")
CLUSTERS_DIR = os.path.join(REPO_ROOT, "infrastructure", "clusters")


def tf_output(name):
    """Run `terraform output -json <name>` and return parsed JSON."""
    result = subprocess.run(
        ["terraform", f"-chdir={INFRA_DIR}", "output", "-json", name],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        print(f"ERROR: terraform output {name} failed:\n{result.stderr}", file=sys.stderr)
        sys.exit(1)
    return json.loads(result.stdout)


def write_tenant_vars(tenants, tenants_config):
    """Write infrastructure/clusters/{tenant}/vars/tenant-vars.yaml for each tenant."""
    for tenant in tenants:
        name = tenant["name"]
        if name not in tenants_config:
            print(f"  WARNING: tenant '{name}' not found in tenants_config output, skipping")
            continue

        cfg = tenants_config[name]
        vars_dir = os.path.join(CLUSTERS_DIR, name, "vars")
        os.makedirs(vars_dir, exist_ok=True)

        doc = {
            "apiVersion": "v1",
            "kind": "ConfigMap",
            "metadata": {
                "name": "tenant-vars",
                "annotations": {"config.kubernetes.io/local-config": "true"},
            },
            "data": {
                "tenant_uuid": cfg["project_id"],
                "vpc_name": cfg["vpc_name"],
            },
        }

        path = os.path.join(vars_dir, "tenant-vars.yaml")
        with open(path, "w") as f:
            f.write("# Generated by scripts/generate-details.py — do not edit manually.\n")
            f.write("# Re-run `make generate-details` after `make apply-infra`.\n\n")
            f.write(yaml.dump(doc, default_flow_style=False, sort_keys=False))
        print(f"  wrote {os.path.relpath(path, REPO_ROOT)}")


def write_cluster_details(namespaces_config):
    """Fill namespace and argo_namespace fields in each cluster-details.yaml.

    For each cluster that has a cluster-values.yaml, reads namespace_ref from that
    file (the lookup key), finds the matching entry in namespaces_config, and writes
    the resolved namespace IDs into cluster-details.yaml.
    """
    # Build a lookup: namespace name (e.g. "dev-1") → namespaces_config entry
    ns_by_name = {}
    for key, val in namespaces_config.items():
        # key is "{tenant}-{ns}" e.g. "tenant-1-dev-1"; ns_name is the namespace logical name
        ns_by_name[val["namespace_name"]] = val

    for root, dirs, files in os.walk(CLUSTERS_DIR):
        if "cluster-values.yaml" not in files:
            continue
        if "cluster-details.yaml" not in files:
            print(f"  WARNING: {root} has cluster-values.yaml but no cluster-details.yaml, skipping")
            continue

        values_path  = os.path.join(root, "cluster-values.yaml")
        details_path = os.path.join(root, "cluster-details.yaml")

        with open(values_path) as f:
            # Strip ytt directives before parsing as plain YAML
            raw = "\n".join(
                line for line in f.read().splitlines()
                if not line.startswith("#@") and not line.startswith("#!")
            )
        values = yaml.safe_load(raw)
        namespace_ref = values.get("namespace_ref", "")

        if not namespace_ref:
            print(f"  WARNING: {os.path.relpath(values_path, REPO_ROOT)} has no namespace_ref, skipping")
            continue

        if namespace_ref not in ns_by_name:
            print(f"  WARNING: namespace_ref '{namespace_ref}' not found in namespaces_config, skipping")
            continue

        ns_cfg = ns_by_name[namespace_ref]

        with open(details_path) as f:
            details = yaml.safe_load(f)

        details["data"]["namespace"]      = ns_cfg["namespace_name"]
        # argo_namespace is the actual generated name of the infra namespace
        details["data"]["argo_namespace"] = ns_cfg["argo_namespace"]

        with open(details_path, "w") as f:
            f.write("# Generated by scripts/generate-details.py — do not edit manually.\n")
            f.write("# Re-run `make generate-details` after `make apply-infra`.\n\n")
            f.write(yaml.dump(details, default_flow_style=False, sort_keys=False))
        print(f"  wrote {os.path.relpath(details_path, REPO_ROOT)}")


def main():
    tenants = yaml.safe_load(open(TENANTS_FILE))["tenants"]

    print("Fetching Terraform outputs...")
    tenants_config    = tf_output("tenants_config")
    namespaces_config = tf_output("namespaces_config")

    print("\nWriting tenant vars...")
    write_tenant_vars(tenants, tenants_config)

    print("\nWriting cluster details...")
    write_cluster_details(namespaces_config)

    print("\nDone. Review and commit generated files.")


if __name__ == "__main__":
    main()
