#!/usr/bin/env python3
"""Generate per-tenant ArgoCD AppProject files and vars directory scaffolding from tenants.yaml.
Run via: make generate
"""

import os, subprocess, sys, yaml

REPO_ROOT    = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TENANTS_FILE = os.path.join(REPO_ROOT, "terraform", "infra", "tenants.yaml")
PROJECTS_DIR = os.path.join(REPO_ROOT, "argocd", "projects")
CLUSTERS_DIR = os.path.join(REPO_ROOT, "infrastructure", "clusters")
TENANT_TMPL  = os.path.join(REPO_ROOT, "templates", "tenant")
HEADER       = ("# Generated by scripts/generate-infra.py via ytt — do not edit manually.\n"
                "# Re-run `make generate` after editing terraform/infra/tenants.yaml.\n\n")


def ytt(tmpl_file, *args):
    result = subprocess.run(
        ["ytt", "-f", os.path.join(TENANT_TMPL, tmpl_file), *args],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        print(f"ERROR: ytt failed:\n{result.stderr}", file=sys.stderr)
        sys.exit(1)
    return HEADER + result.stdout


def project_yaml(tenant):
    return ytt(
        "project.yaml",
        "--data-value", f"name={tenant['name']}",
        "--data-value", f"type={tenant.get('type', 'tenant')}",
    )


def projects_kustomization():
    return ytt("kustomization.yaml", "--data-values-file", TENANTS_FILE)


def vars_kustomization():
    return (
        "# Generated by scripts/generate-infra.py — do not edit manually.\n\n"
        "apiVersion: kustomize.config.k8s.io/v1beta1\n"
        "kind: Kustomization\n\n"
        "resources:\n"
        "- tenant-vars.yaml\n"
    )


def main():
    tenants = yaml.safe_load(open(TENANTS_FILE))["tenants"]

    for tenant in tenants:
        name = tenant["name"]

        project_path = os.path.join(PROJECTS_DIR, f"{name}.yaml")
        with open(project_path, "w") as f:
            f.write(project_yaml(tenant))
        print(f"  wrote {os.path.relpath(project_path, REPO_ROOT)}")

        vars_dir = os.path.join(CLUSTERS_DIR, name, "vars")
        os.makedirs(vars_dir, exist_ok=True)
        kust_path = os.path.join(vars_dir, "kustomization.yaml")
        if not os.path.exists(kust_path):
            with open(kust_path, "w") as f:
                f.write(vars_kustomization())
            print(f"  wrote {os.path.relpath(kust_path, REPO_ROOT)}")
        else:
            print(f"  skipped {os.path.relpath(kust_path, REPO_ROOT)} (already exists)")

    kust_path = os.path.join(PROJECTS_DIR, "kustomization.yaml")
    with open(kust_path, "w") as f:
        f.write(projects_kustomization())
    print(f"  wrote {os.path.relpath(kust_path, REPO_ROOT)}")

    print(f"\n{len(tenants)} tenant(s) generated. Review and commit.")


if __name__ == "__main__":
    main()
