#!/usr/bin/env python3
"""Regenerate terraform/bootstrap/providers.tf and main.tf from tenants.yaml.
Run via: make generate
"""

import yaml
from jinja2 import Environment, FileSystemLoader
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
HEADER = (
    "# Generated by scripts/generate-bootstrap.py — do not edit manually.\n"
    "# Re-run `make generate` after editing terraform/infra/tenants.yaml.\n\n"
)


def main():
    tenants = yaml.safe_load((REPO_ROOT / "terraform/infra/tenants.yaml").read_text())["tenants"]
    env = Environment(loader=FileSystemLoader(str(REPO_ROOT / "templates/bootstrap")))
    env.filters["tf_id"] = lambda s: s.replace("-", "_")
    env.filters["tf_bool"] = lambda v: "true" if v else "false"

    for tmpl_name, out_path in [
        ("providers.tf.j2", "terraform/bootstrap/providers.tf"),
        ("main.tf.j2", "terraform/bootstrap/main.tf"),
    ]:
        out = REPO_ROOT / out_path
        out.write_text(HEADER + env.get_template(tmpl_name).render(tenants=tenants))
        print(f"  wrote {out_path}")

    ns_count = sum(len(t.get("namespaces", [])) for t in tenants)
    print(f"\n{ns_count} namespace(s) generated. Review and commit.")


if __name__ == "__main__":
    main()
