#!/usr/bin/env python3
"""Regenerate terraform/bootstrap/providers.tf and main.tf from tenants.yaml.
Run via: make generate
"""

import os, yaml

REPO_ROOT     = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TENANTS_FILE  = os.path.join(REPO_ROOT, "terraform", "infra", "tenants.yaml")
BOOTSTRAP_DIR = os.path.join(REPO_ROOT, "terraform", "bootstrap")
HEADER        = ("# Generated by scripts/generate-bootstrap.py — do not edit manually.\n"
                 "# Re-run `make generate` after editing terraform/infra/tenants.yaml.\n\n")


def tf_id(s):
    return s.replace("-", "_")


def each_ns(tenants):
    for t in tenants:
        for ns in t.get("namespaces", []):
            yield t, ns


def provider_block(t, ns):
    key   = f"{t['name']}-{ns['name']}"
    alias = tf_id(key)
    return f"""\
provider "helm" {{
  alias = "{alias}"
  kubernetes {{
    host     = var.kubeconfigs["{key}"].host
    token    = var.kubeconfigs["{key}"].token
    insecure = var.kubeconfigs["{key}"].insecure_skip_tls_verify
  }}
}}
"""


def module_block(t, ns):
    key    = f"{t['name']}-{ns['name']}"
    alias  = tf_id(key)
    labels = "\n".join(f'    {k} = "{v}"' for k, v in ns.get("argo_labels", {}).items())
    return f"""\
module "bootstrap_{alias}" {{
  source = "../modules/bootstrap-helm"

  providers = {{ helm = helm.{alias} }}

  namespace           = "{ns['name']}"
  tenant_name         = "{t['name']}"
  deploy_argo         = {str(ns.get("deploy_argo", False)).lower()}
  argo_namespace      = "{t.get('argo_namespace', 'argocd')}"
  argo_password       = var.argo_password
  root_app_url        = var.repo_url
  argo_cluster_labels = {{
{labels}
  }}
  ako_secret_enabled  = var.ako_secret_enabled
  ako_username        = var.ako_username
  ako_password        = var.ako_password
  ako_ca_data         = var.ako_ca_data
}}
"""


def write(path, blocks):
    with open(path, "w") as f:
        f.write(HEADER + "\n".join(blocks))
    print(f"  wrote {os.path.relpath(path, REPO_ROOT)}")


def main():
    tenants = yaml.safe_load(open(TENANTS_FILE))["tenants"]
    pairs   = list(each_ns(tenants))
    write(os.path.join(BOOTSTRAP_DIR, "providers.tf"), [provider_block(t, ns) for t, ns in pairs])
    write(os.path.join(BOOTSTRAP_DIR, "main.tf"),      [module_block(t, ns)   for t, ns in pairs])
    print(f"\n{len(pairs)} namespace(s) generated. Review and commit.")


if __name__ == "__main__":
    main()
