apiVersion: v1
kind: ConfigMap
metadata:
  name: vars
  annotations:
    config.kubernetes.io/local-config: 'true'
data:
  cluster_name: dev1-cluster   # must equal this directory name
  project: tenant-1            # must equal the {project} directory & cluster label
  namespace_ref: dev-1         # must equal the {namespace_ref} directory & cluster label
