apiVersion: v1
kind: Secret
metadata:
 name: cluster-avi-secret
 labels:
   config.k8s.io/inject-cluster-name-prefix: "true"
type: Opaque
data:
 username: YWRtaW4=
 password: Vk13YXJlMTIzIVZNd2FyZTEyMyE=
 certificateAuthorityData: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUUrVENDQXVHZ0F3SUJBZ0lJTVRaelJ3UUZBUmd3RFFZSktvWklodmNOQVFFTEJRQXdZREVMTUFrR0ExVUVCaE1DVlZNeEN6QUpCZ05WQkFnTUFrTkJNUkl3RUFZRFZRUUhEQWxRWVd4dklFRnNkRzh4RVRBUEJnTlZCQW9NQ0VKeWIyRmtZMjl0TVF3d0NnWURWUVFMREFOc1lXSXhEekFOQmdOVkJBTU1CblpqWm14aFlqQWVGdzB5TmpBeE1EY3hPREl6TlRWYUZ3MHlOekF5TURneE9ESXpOVFZhTUd3eEN6QUpCZ05WQkFZVEFsVlRNUXN3Q1FZRFZRUUlEQUpEUVRFU01CQUdBMVVFQnd3SlVHRnNieUJCYkhSdk1SRXdEd1lEVlFRS0RBaENjbTloWkdOdmJURVBNQTBHQTFVRUN3d0dkbU5tYkdGaU1SZ3dGZ1lEVlFRRERBOWhkbWt0ZDJ4a0xuWmpaaTVzWVdJd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNLV2pjblZzdkN3djRwdWdQSDQ2T1NYUlJqQ3dpS0FRQUdjKzNzUVVwdHYxSUxBR3RwNlg0NndtdFZFcW9MbUYwR0M4ODVEbS9qTWltT1Vic3VPVzNHMk5NRktnSW51UCt2K2YrbDhpVEZXakc3QmVjVXdzZjF2TUIySHliNG55bXZZVERxNTBaUGdpTWU5aHhNTWlpSjBmTDluK2RDSFMzNkJ6c3duTFZFTjcyeDViNFNjR2FLR2x6WGx4MGp3K0s5a3BaWDlUb3B4cWVRSGNjaFBNeFcrdW8wS0RVNm1SeEk3RWJtOXlRY0EvQVphU3hrM2taTC9vaGg1VUlKdXgrYXF4Nks5eXYzVS96c2w1R1RvUFRDc0J4Q2pQSUpmYWRQSUZ1eXRRMGFtVmtqZ0dtK2FHZWllSm1aaGtRRnpTWkpQYnV2K0thbGRtVGVROUoydXoreEFnTUJBQUdqZ2Fvd2dhY3dDUVlEVlIwVEJBSXdBREFkQmdOVkhRNEVGZ1FVYzIwNE5FQldmU2ZJQ3dMeGFobEtKZzl1aGdvd0h3WURWUjBqQkJnd0ZvQVVCQ0o3WFlQWlpDaEdWNWJHOTZpRnZPTVU0RlF3Q3dZRFZSMFBCQVFEQWdYZ01FMEdBMVVkRVFSR01FU0hCQW9BQUphSEJBb0FBSmVDRVdGMmFUQXhMWGRzWkM1MlkyWXViR0ZpZ2dkaGRta3RkMnhrZ2dsaGRta3dNUzEzYkdTQ0QyRjJhUzEzYkdRdWRtTm1MbXhoWWpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQWpxYk0zUTUxMEVDQlpNUmMydEFHWmNuakkwbU1rVXZpZ3lsMnIzdnhJTzJwWU5UYlJaR05SbzRRUWt0bHcwblc0T0wvcUIrN0YxRGk1Zi9nV3VSbTc2L3owaVF6MlpHS1BtemN1blJ1aEsvMkxhMEh0dE9VaEpqU2tzSDRsYTA5Y2dhcFc0cXA2Q29reDc3aUwvREFwN0NjOGNQVXNkdi82UTRnSnVwbzZMSEhPZEVWVFg4aHYwNy9IQkJsV2VwVUZxTmFzNDluNkRKL0poNitnMGVUNXF5Z2FBVloxUFVsT1dBa1EzZUpmNWw0d2ZNck5yNWxEZ0VsSVNTME1IeEdPMFpiUHpjZ1ZHb21yWUNDU09yOFlsaG9CWGF5LzJQTEdudVdLcWNsbzFxVXhhZGhXa1lYSWtpc3F2d0VTeE1wd0RMRkpqYnAvd2o0L2gvRDgyR0JTUXdZb1F6WVNkMmtIQ0hZa2hPSUw3bEZpb0lKVnVHbytrVXdlckZzSzdmMDYvZjVoRy9uTStSTm9HOU4zTmVxaWhabngyaDV3ZzNlN2NGckpudXRhQmZMbStOZFdFUTlDVXNTKys3Ym4wd2xSZmdwMysvRURPNFkzN016S3UxbGZ1NVVGOGQrMzJOaXIrdUNKSjlpRldjb2xBY3VNakZDUTVBdWlmWEo4eHdUWCtsQkh2dXcySjNlenJvaVIySVN6bE9USkRsaGkwK3RJeDdzN1Y4YmttMU5xLzkxOVRFTUdHVG9TWXRHd0ZPS2pkeDJaYjBaSlYzRkxCS3UyVmVWZ0Z3eEsxTXltQTgzcGdjQk9wWGpkT3V1emxTWFo4Ym9sUDBBN1NSUlo2WTkrRFFzMU1zNHRLNWUzZmFDc216ZHVpZmNBRWxwaVJPOXdRQ2l3WFBnRzgwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
---
apiVersion: addons.kubernetes.vmware.com/v1alpha1
kind: AddonConfig
metadata:
  name: cluster-ako
  labels:
    app.kubernetes.io/name: ako
    config.k8s.io/inject-cluster-name-prefix: "true"
spec:
  addonConfigDefinitionRef:
     name: ako.kubernetes.vmware.com.2.1.3+vmware.1-vks.1 # Ensure this matches your available version
     namespace: vmware-system-vks-public
  values:
    AKOSettings:
      clusterName: cluster         
      vpcMode: true
      istioEnabled: false

    ControllerSettings:
      controllerHost: "10.0.0.150"  
      cloudName: "nsx-wld-cloud"    
      tenantName: "replace-me"     

    NetworkSettings:
  
      nsxtT1LR: "/orgs/default/projects/replace-me/vpcs/replace-me" 
---
apiVersion: addons.kubernetes.vmware.com/v1alpha1
kind: AddonInstall
metadata:
  name: cluster-ako-installer
  labels:
    app.kubernetes.io/name: ako
    config.k8s.io/inject-cluster-name-prefix: "true"
  annotations:
    argocd.argoproj.io/sync-wave: '2'
spec:
  addonRef:
    name: ako
  clusters:
  - selector:
      matchLabels:
        cluster.x-k8s.io/cluster-name: cluster 
  paused: false
