apiVersion: v1
kind: Secret
metadata:
  name: cluster-avi-secret
  labels:
    config.k8s.io/inject-cluster-name-prefix: "true"
type: Opaque
data:
  # Base64 encoded credentials
  username: YWRtaW4=                 # <--- UPDATE THIS: Base64 encoded AVI username (e.g. 'admin')
  password: Vk13YXJlMTIzIVZNd2FyZTEyMyE=  # <--- UPDATE THIS: Base64 encoded AVI password
  certificateAuthorityData: LS0t...  # <--- UPDATE THIS: Base64 encoded Root CA Data. This can be pulled from AVI under templates->security->tls/ssl->root
---
apiVersion: addons.kubernetes.vmware.com/v1alpha1
kind: AddonConfig
metadata:
  name: cluster-ako
  labels:
    app.kubernetes.io/name: ako
    config.k8s.io/inject-cluster-name-prefix: "true"
spec:
  addonConfigDefinitionRef:
     name: ako.kubernetes.vmware.com.2.1.3+vmware.1-vks.1 # Ensure this matches your available version
     namespace: vmware-system-vks-public
  values:
    AKOSettings:
      clusterName: cluster         # <--- UPDATE THIS: Your VKS Cluster Name
      vpcMode: true
      istioEnabled: false

    ControllerSettings:
      controllerHost: "10.0.0.150"   # <--- UPDATE THIS: AVI Controller IP
      cloudName: "nsx-wld-cloud"     # <--- UPDATE THIS
      tenantName: "replace-me"     # <--- UPDATE THIS: Your Tenant UUID

    NetworkSettings:
      # Paste the NSX VPC Path retrieved in Step 4.1 below
      nsxtT1LR: "/orgs/default/projects/replace-me/vpcs/replace-me" # <--- UPDATE THIS
---
apiVersion: addons.kubernetes.vmware.com/v1alpha1
kind: AddonInstall
metadata:
  name: cluster-ako-installer
  labels:
    app.kubernetes.io/name: ako
    config.k8s.io/inject-cluster-name-prefix: "true"
spec:
  addonRef:
    name: ako
  clusters:
  - selector:
      matchLabels:
        cluster.x-k8s.io/cluster-name: cluster  # <--- UPDATE THIS: Your VKS Cluster Name
  paused: false
